const config = {
  url: 'https://api.newsyp.tk',
  login: 'https://api.newsyp.tk/signin',
  signup: 'https://api.newsyp.tk/signup',
  logout: 'https://api.newsyp.tk/logout',
  getUser: 'https://api.newsyp.tk/users/me',
  articles: 'https://api.newsyp.tk/articles',
  git: 'https://github.com/snegmen/news-explorer-frontend/commits',
  maxGitCommits: 15,
  month: ['января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 'июля', 'августа',
    'сентября', 'октября', 'ноября', 'декабря'],
  newsFeed: 'https://newsapi.org/v2/everything?sortBy=popularity&apiKey=61e9a15929844de49c00be490b903f34&language=ru&pageSize=100',
  showMore: { node: '#show-more', hide: 'results__button_hide' },
  showStep: 3,
  cardSample: '#card-sample',
  card: {
    node: '.card',
    img: '.card__picture',
    date: '.card__date',
    title: '.card__title',
    text: '.card__text',
    src: '.card__source',
    warning: '.card__balloon',
    keyword: '.card__keyword',
    icon: {
      node: '.card__icon',
      logged: 'card__icon_logged',
      marked: 'card__icon_saved',
      bin: 'card__icon_del',
    },
  },
  resultsField: '.results__articles',
  newsForm: 'news-finder',
  newsFormSearchField: 'search',
  preloader: { node: '#preloader-searching', hide: 'preloader__wrapper_hide' },
  notFound: { node: '#preloader-not-found', hide: 'preloader__wrapper_hide' },
  serverError: { node: '#preloader-server-error', hide: 'preloader__wrapper_hide' },
  resultsSection: { node: '.results', hide: 'results_hide' },
  collectionContainer: '.saved-articles',
  articlesQty: '.articles-qty',
  articlesHeader: '.saved-description__title',
  words: {
    first: '.first-word',
    second: '.second-word',
    more: '.and-more',
    tail: '.word-tail',
  },
};

export default config;
